# Generated by Django 6.0.1 on 2026-01-09 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PathOfSpeech",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_main", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="SubtitleList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("is_open_menu", models.BooleanField(default=False)),
                ("is_hide", models.BooleanField(default=False)),
                ("quantity_words", models.PositiveIntegerField(default=0)),
                ("quantity_words_frequencies", models.PositiveIntegerField(default=0)),
                ("quantity_learned_words", models.PositiveIntegerField(default=0)),
                (
                    "quantity_learned_words_frequencies",
                    models.PositiveIntegerField(default=0),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("modified_time", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "transcription",
                    models.CharField(blank=True, default="", max_length=30),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "translation",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("is_main", models.BooleanField(default=False)),
                (
                    "path_of_speech",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="lists.pathofspeech",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserSubtitleList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subtitle_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lists.subtitlelist",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "subtitle_list")},
            },
        ),
        migrations.AddField(
            model_name="subtitlelist",
            name="users",
            field=models.ManyToManyField(
                related_name="subtitle_lists",
                through="lists.UserSubtitleList",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="SubtitleListWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frequency", models.PositiveIntegerField(default=1)),
                (
                    "subtitle_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="word_links",
                        to="lists.subtitlelist",
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtitle_links",
                        to="lists.word",
                    ),
                ),
            ],
            options={
                "unique_together": {("subtitle_list", "word")},
            },
        ),
        migrations.AddField(
            model_name="subtitlelist",
            name="words",
            field=models.ManyToManyField(
                related_name="subtitle_lists",
                through="lists.SubtitleListWord",
                to="lists.word",
            ),
        ),
        migrations.AddField(
            model_name="pathofspeech",
            name="word",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parts_of_speech",
                to="lists.word",
            ),
        ),
    ]
