# Generated by Django 6.0.1 on 2026-01-24 11:15

from django.db import migrations, models

from apps.lists.models import subtitle_list_image_path


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0002_subtitlelist_is_public_subtitlelist_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subtitlelist",
            name="background_color",
            field=models.CharField(
                default="#ffffff",
                help_text="CSS цвет фона (например: #ffffff)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="subtitlelist",
            name="background_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=subtitle_list_image_path
            ),
        ),
    ]
