# Generated by Django 6.0.1 on 2026-01-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0004_knownword"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pathofspeech",
            name="name",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="word",
            name="name",
            field=models.CharField(
                blank=True, db_index=True, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="transcription",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
