# Generated by Django 6.0.1 on 2026-02-01 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0001_initial"),
        ("lists", "0005_alter_pathofspeech_name_alter_word_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pathofspeech",
            name="word",
        ),
        migrations.RemoveField(
            model_name="translation",
            name="path_of_speech",
        ),
        migrations.AlterUniqueTogether(
            name="subtitlelistlike",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="subtitlelistlike",
            name="subtitle_list",
        ),
        migrations.RemoveField(
            model_name="subtitlelistlike",
            name="user",
        ),
        migrations.AlterField(
            model_name="subtitlelistword",
            name="word",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtitle_links",
                to="dictionary.word",
            ),
        ),
        migrations.AlterField(
            model_name="subtitlelist",
            name="words",
            field=models.ManyToManyField(
                related_name="subtitle_lists",
                through="lists.SubtitleListWord",
                to="dictionary.word",
            ),
        ),
        migrations.DeleteModel(
            name="KnownWord",
        ),
        migrations.DeleteModel(
            name="PathOfSpeech",
        ),
        migrations.DeleteModel(
            name="Translation",
        ),
        migrations.DeleteModel(
            name="SubtitleListLike",
        ),
        migrations.DeleteModel(
            name="Word",
        ),
    ]
